### ISSUE TITLE
fetchProductsFromCollection is only fetching the first page of the specified collection(s)

### ISSUE THREAD

**Issue by jinftw64** [EcomGraduates/shopify-product-export-to-csv#1]
fetchProductsFromCollection is only fetching the first page of the specified collection(s).

**Comment by EcomGraduates** [comment]
probably needs to be updated. you can do it if you'd like and submit a PR!

**Comment by jinftw64** [comment]
This was my first PR ever! Thank you for your work on this project. It has been very helpful for the Shopify site that I'm creating for a client.
